# Generated by Django 3.2.17 on 2023-02-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('affair', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('importance', models.CharField(choices=[('3', 'Duda Importante'), ('1', 'Relativamente Importante'), ('2', 'Poco Importante'), ('0', 'Muy Importante')], max_length=1)),
            ],
        ),
    ]
