# Generated by Django 3.2.17 on 2023-02-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='importance',
            field=models.CharField(choices=[('2', 'Poco Importante'), ('0', 'Muy Importante'), ('3', 'Duda Importante'), ('1', 'Relativamente Importante')], max_length=1),
        ),
    ]
