# Generated by Django 3.2.17 on 2023-02-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactmodel_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='importance',
            field=models.CharField(choices=[('1', 'Relativamente Importante'), ('3', 'Duda'), ('0', 'Muy Importante'), ('2', 'Poco Importante')], max_length=1),
        ),
    ]
